# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  wozbevragenproxy:
    container_name: wozbevragenproxy
    image: ghcr.io/vng-realisatie/wozbevragen-proxy
    build:
      context: .
      dockerfile: src/Woz.BevragenProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
    # volumes:
    #   - ./src/config/Woz.BevragenProxy:/app/config

  wozbevragenmock:
    container_name: wozbevragenmock
    image: ghcr.io/melvlee/wozbevragen-mock
    build:
      context: .
      dockerfile: src/Woz.BevragenMock/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - 5010:5010
